import type { Question, MBTILetter } from './types.js';

export const questions: Question[] = [
  { id: 1,  text: "Prefiero pasar tiempo con grupos grandes de personas.", column: 1, dim: 'E/I' },
  { id: 2,  text: "Me fijo más en los detalles concretos y hechos reales.", column: 2, dim: 'S/N' },
  { id: 3,  text: "Me gusta describir las cosas de manera precisa y detallada.", column: 3, dim: 'S/N' },
  { id: 4,  text: "Tomo decisiones basándome en la lógica y la razón.", column: 4, dim: 'T/F' },
  { id: 5,  text: "Me considero una persona justa y objetiva.", column: 5, dim: 'T/F' },
  { id: 6,  text: "Me gusta tener un plan y seguirlo estrictamente.", column: 6, dim: 'J/P' },
  { id: 7,  text: "Me estresa la incertidumbre y la falta de planes.", column: 7, dim: 'J/P' },
  { id: 8,  text: "Me siento con energía después de asistir a una fiesta o reunión social.", column: 1, dim: 'E/I' },
  { id: 9,  text: "Confío más en la información que proviene de mis experiencias directas.", column: 2, dim: 'S/N' },
  { id: 10, text: "Cuando leo, prefiero historias basadas en hechos reales.", column: 3, dim: 'S/N' },
  { id: 11, text: "Es más importante ser honesto que ser diplomático.", column: 4, dim: 'T/F' },
  { id: 12, text: "Analizo los pros y contras antes de decidir.", column: 5, dim: 'T/F' },
  { id: 13, text: "Prefiero que mi vida esté estructurada y organizada.", column: 6, dim: 'J/P' },
  { id: 14, text: "Cierro capítulos y tomo decisiones definitivas.", column: 7, dim: 'J/P' },
  { id: 15, text: "Disfruto conocer gente nueva y entablar conversaciones casuales.", column: 1, dim: 'E/I' },
  { id: 16, text: "Prefiero instrucciones paso a paso y claras.", column: 2, dim: 'S/N' },
  { id: 17, text: "Para tomar decisiones, me baso en información verificable.", column: 3, dim: 'S/N' },
  { id: 18, text: "Cuando resuelvo problemas, uso un enfoque analítico.", column: 4, dim: 'T/F' },
  { id: 19, text: "Valoro más la competencia y la eficiencia.", column: 5, dim: 'T/F' },
  { id: 20, text: "Me gusta tener las cosas decididas con anticipación.", column: 6, dim: 'J/P' },
  { id: 21, text: "Me siento incómodo cuando las cosas cambian de último minuto.", column: 7, dim: 'J/P' },
  { id: 22, text: "Suelo pensar en voz alta mientras organizo mis ideas.", column: 1, dim: 'E/I' },
  { id: 23, text: "Me gusta trabajar con hechos, datos y evidencia concreta.", column: 2, dim: 'S/N' },
  { id: 24, text: "Disfruto más las experiencias sensoriales (comida, música, arte visual).", column: 3, dim: 'S/N' },
  { id: 25, text: "Prefiero que me digan la verdad aunque sea dura.", column: 4, dim: 'T/F' },
  { id: 26, text: "Prefiero ambientes donde predomine la lógica.", column: 5, dim: 'T/F' },
  { id: 27, text: "Hago listas y horarios para organizar mis actividades.", column: 6, dim: 'J/P' },
  { id: 28, text: "Establezco metas claras y trabajo para alcanzarlas.", column: 7, dim: 'J/P' },
  { id: 29, text: "Prefiero trabajos que impliquen interactuar con muchas personas.", column: 1, dim: 'E/I' },
  { id: 30, text: "Presto atención a lo que sucede aquí y ahora.", column: 2, dim: 'S/N' },
  { id: 31, text: "Soy más consciente de mi entorno físico inmediato.", column: 3, dim: 'S/N' },
  { id: 32, text: "Juzgo las situaciones basándome en principios objetivos.", column: 4, dim: 'T/F' },
  { id: 33, text: "Las decisiones deben basarse en hechos objetivos.", column: 5, dim: 'T/F' },
  { id: 34, text: "Me siento más productivo cuando sigo una rutina.", column: 6, dim: 'J/P' },
  { id: 35, text: "Me gusta tener claridad sobre lo que haré cada día.", column: 7, dim: 'J/P' },
  { id: 36, text: "En reuniones, soy de los que más hablan y participan.", column: 1, dim: 'E/I' },
  { id: 37, text: "Prefiero aprender a través de la práctica y la experiencia directa.", column: 2, dim: 'S/N' },
  { id: 38, text: "Prefiero los pasatiempos que producen resultados tangibles.", column: 3, dim: 'S/N' },
  { id: 39, text: "Tiendo a ser objetivo e imparcial en mis decisiones.", column: 4, dim: 'T/F' },
  { id: 40, text: "Suelo decir lo que pienso directamente.", column: 5, dim: 'T/F' },
  { id: 41, text: "Prefiero trabajos con plazos y metas claras.", column: 6, dim: 'J/P' },
  { id: 42, text: "Prefiero eventos con horarios definidos y estructura.", column: 7, dim: 'J/P' },
  { id: 43, text: "Me resulta fácil iniciar conversaciones con desconocidos.", column: 1, dim: 'E/I' },
  { id: 44, text: "Me considero una persona práctica y realista.", column: 2, dim: 'S/N' },
  { id: 45, text: "Me considero una persona realista.", column: 3, dim: 'S/N' },
  { id: 46, text: "Me molestan las injusticias y las incoherencias lógicas.", column: 4, dim: 'T/F' },
  { id: 47, text: "Cuando alguien tiene un problema, ofrezco soluciones prácticas.", column: 5, dim: 'T/F' },
  { id: 48, text: "Tengo un lugar para cada cosa y cada cosa en su lugar.", column: 6, dim: 'J/P' },
  { id: 49, text: "El orden y la organización son esenciales para mí.", column: 7, dim: 'J/P' },
  { id: 50, text: "Prefiero actividades grupales que individuales.", column: 1, dim: 'E/I' },
  { id: 51, text: "Disfruto más cuando me enfoco en una tarea a la vez.", column: 2, dim: 'S/N' },
  { id: 52, text: "Me gusta que las cosas sean medibles y cuantificables.", column: 3, dim: 'S/N' },
  { id: 53, text: "Las críticas constructivas me ayudan a mejorar.", column: 4, dim: 'T/F' },
  { id: 54, text: "Me siento más cómodo con el debate intelectual.", column: 5, dim: 'T/F' },
  { id: 55, text: "Planifico mis vacaciones con itinerarios detallados.", column: 6, dim: 'J/P' },
  { id: 56, text: "Cuando empiezo un libro o proyecto, lo termino antes de empezar otro.", column: 7, dim: 'J/P' },
  { id: 57, text: "Disfruto ser el centro de atención en eventos sociales.", column: 1, dim: 'E/I' },
  { id: 58, text: "Valoro más la utilidad práctica de las cosas.", column: 2, dim: 'S/N' },
  { id: 59, text: "Aprendo mejor cuando veo ejemplos prácticos.", column: 3, dim: 'S/N' },
  { id: 60, text: "Defiendo mis decisiones con argumentos lógicos.", column: 4, dim: 'T/F' },
  { id: 61, text: "Prefiero líderes que sean firmes y decisivos.", column: 5, dim: 'T/F' },
  { id: 62, text: "Me gusta terminar un proyecto antes de comenzar otro.", column: 6, dim: 'J/P' },
  { id: 63, text: "Me siento mejor cuando mi entorno está ordenado.", column: 7, dim: 'J/P' },
  { id: 64, text: "Tengo muchos amigos y conocidos con quienes me mantengo en contacto.", column: 1, dim: 'E/I' },
  { id: 65, text: "Prefiero rutinas y métodos probados.", column: 2, dim: 'S/N' },
  { id: 66, text: "Prefiero conversaciones sobre temas cotidianos y concretos.", column: 3, dim: 'S/N' },
  { id: 67, text: "Resuelvo conflictos estableciendo reglas claras.", column: 4, dim: 'T/F' },
  { id: 68, text: "La verdad objetiva es más importante que la armonía del grupo.", column: 5, dim: 'T/F' },
  { id: 69, text: "La puntualidad y el cumplimiento de plazos son fundamentales.", column: 6, dim: 'J/P' },
  { id: 70, text: "Las reglas y normas existen para cumplirse.", column: 7, dim: 'J/P' }
];

export const columnMap: Record<number, { A: MBTILetter; B: MBTILetter }> = {
  1: { A: 'E', B: 'I' },
  2: { A: 'S', B: 'N' },
  3: { A: 'S', B: 'N' },
  4: { A: 'T', B: 'F' },
  5: { A: 'T', B: 'F' },
  6: { A: 'J', B: 'P' },
  7: { A: 'J', B: 'P' }
};

export const dimensionPairs: Array<{ l: MBTILetter; r: MBTILetter; label: string }> = [
  { l: 'E', r: 'I', label: 'Extroversión / Introversión' },
  { l: 'S', r: 'N', label: 'Sensorial / Intuitivo' },
  { l: 'T', r: 'F', label: 'Racional / Emocional' },
  { l: 'J', r: 'P', label: 'Estructurado / Perceptivo' }
];
